theme: minima 
title: MEMES! and why they're so cool
author: Phoebe 
email: phoebegyebi68@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Memes are epic and we'll be finding out why 
# social links
twitter_username: Anscrimy # DO NOT include the @ character, or else the build will fail!
github_username:  Phoebethesuper # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
