title: Memes and why theyre awsome
author: GitHub User
email: phoebegyebi68@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  MEMES are AWSOME and we're gonna figure out why
# social links
twitter_username: Anscrimy # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
